<?php

namespace App\Integrations\Fidelity;

use App\Models\Stand;
use Barryvdh\DomPDF\Facade\Pdf;

/**
 * Development stand-in for Fidelity Life's API. Any stand that exists in the
 * stands table matches when the national ID is well-formed; the phone on file
 * is derived from the stand number so tests are deterministic.
 */
class FakeFidelityClient implements FidelityClient
{
    public function match(string $nationalId, string $standNumber): array
    {
        if (app()->isProduction()) {
            throw new \RuntimeException('The fake Fidelity driver cannot be used in production. Use FIDELITY_DRIVER=manual or http.');
        }
        $stand = Stand::where('stand_number', $standNumber)->first();
        if (! $stand || ! preg_match('/^\d{2}-?\d{6,7}-?[A-Z]-?\d{2}$/i', $nationalId)) {
            return ['matched' => false];
        }
        $phone = '+26377'.str_pad((string) (crc32($standNumber) % 10000000), 7, '0', STR_PAD_LEFT);

        return [
            'matched' => true,
            'reference' => 'FL-'.strtoupper(substr(sha1($standNumber.$nationalId), 0, 10)),
            'phone' => $phone,
            'phone_masked' => '•••• '.substr($phone, -3),
            'buyer_name' => 'Registered buyer',
        ];
    }

    public function paymentHistory(string $reference): array
    {
        $rows = [];
        $balance = 10000.0;
        $date = now()->subYears(6)->startOfMonth();
        for ($i = 0; $i < 12; $i++) {
            $amount = $i === 0 ? 2000.0 : 666.67;
            $balance = max(0, round($balance - $amount, 2));
            $rows[] = ['date' => $date->copy()->addMonths($i * 3)->toDateString(), 'description' => $i === 0 ? 'Deposit' : 'Instalment', 'amount' => $amount, 'currency' => 'USD', 'balance' => $balance];
        }

        return $rows;
    }

    public function agreementPdf(string $reference): string
    {
        return Pdf::loadHTML('<h1 style="font-family:sans-serif">Agreement of Sale (sample)</h1><p style="font-family:sans-serif">Fidelity Life Assurance of Zimbabwe. Reference '.e($reference).'. This is a development sample generated by the fake Fidelity adapter.</p>')->output();
    }

    public function requestReplacement(string $reference, string $requestReference): bool
    {
        return true;
    }
}
